version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 1d
    command: npm start

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 1d
    command: npm test
